export const RouteEnum = {
  HOME: "/",
  // DASHBOARD: "/",
  FORGOTPASSWORD: "/forgot-password",
  NEWPASSWORD: "/new-password",
  LOGIN: "/login",
  SIGNUP: "/signUp",
  SIGNUPA: "/signups",
  DASHBOARD: "/dashboard",
  SIGNUPCLIENT: "/signup-client",
  MANAGE_COMPANIES: "/history",
  MANAGE_RIDERS: "/wallet",
  TRIPS: "/manage-riders",
  MAPS: "/maps",
  SUPPORT: "/add-riders",
  PROFILE: "/profile",
};
