export const RouteEnum = {
  HOME: "/",
  // DASHBOARD: "/",
  FORGOTPASSWORD: "/forgot-password",
  NEWPASSWORD: "/new-password",
  LOGIN: "/login",
  SIGNUP: "/signUp",
  SIGNUPA: "/signups",
  DASHBOARD: "/dashboard",
  SIGNUPCLIENT: "/signup-client",
  MANAGE_COMPANIES: "/manage-companies",
  MANAGE_RIDERS: "/manage-riders",
  TRIPS: "/trips",
  MAPS: "/maps",
  SUPPORT: "/support",
  PROFILE: "/profile",
};
